[package]
name = "BitcoinToe5"
version = "1.0.0"
authors = []
[addresses]
my_addrx = "34377ce2dff9245600c983f9675f4f86a86fc574405c862c4fb33bc3374da117"
sys_addrx = "34377ce2dff9245600c983f9675f4f86a86fc574405c862c4fb33bc3374da117"
std = "0x1"
[dev-addresses]
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dev-dependencies]